### ISSUE TITLE
Special forms like with-open-input-file and block eval their arguments

### ISSUE THREAD

**Issue by wasamasa** [islisp-dev/iris#5]
Not sure whether it's a systematic issue, but I found that neither of these simple examples work correctly:

```lisp
>>> (with-open-input-file (in "/etc/hostname") (read-line in))
#<DOMAIN-ERROR {IRIS.OBJECT: IN, EXPECTED-CLASS: <STRING>, IRIS.CONTINUABLE: NIL}>
```

```lisp
>>> (block foo (return-from foo 42))
#<UNDEFINED-VARIABLE {NAME: FOO, NAMESPACE: VARIABLE, IRIS.CONTINUABLE: NIL}>
```

Both examples work fine with OpenLisp and return the hostname and 42 respectively. I'm using the latest Iris installed with `go get github.com/asciian/iris` on Arch Linux.

**Comment by tani** [comment]
After two years passed, I finally close this issue. Thanks!
